// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernRecrut.Postulations.Infrastructure.Data;

#nullable disable

namespace ModernRecrut.Postulations.Infrastructure.Migrations
{
    [DbContext(typeof(GestPostulationContext))]
    [Migration("20240205205937_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ModernRecrut.Postulations.ApplicationCore.Entites.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NomEmeteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotePostulation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostulationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostulationId");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("ModernRecrut.Postulations.ApplicationCore.Entites.Postulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateDisponibilite")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdCandidat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OffreEmploiID")
                        .HasColumnType("int");

                    b.Property<decimal>("PretentionSalariale")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Postulation");
                });

            modelBuilder.Entity("ModernRecrut.Postulations.ApplicationCore.Entites.Note", b =>
                {
                    b.HasOne("ModernRecrut.Postulations.ApplicationCore.Entites.Postulation", null)
                        .WithMany("Notes")
                        .HasForeignKey("PostulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModernRecrut.Postulations.ApplicationCore.Entites.Postulation", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
