# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: serviceConnection
    type: string
  - name: location
    type: string
  - name: environnement
    type: string
  - name: bicepfile
    type: string

jobs:
- job: 'Deploiement'
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(serviceConnection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az --version
        az group create --name rg$(environnement) --location $(location)
        az deployment group create --resource-group rg$(environnement) --template-file $(bicepfile) --parameters appName=$(appNameDev)