parameters:
  - name: buildConfiguration
    type: string
  - name: artifactName
    type: string
  - name: appname
    type: string
  - name: publishWebProjects
    type: boolean
    values:
      - false
      - true
    default: false

jobs:
  - job: 'Build'
    pool:
      vmImage: ubuntu-latest

    steps:

  #pour le project MVC:
    - ${{ if eq(parameters.publishWebProjects, true) }}: 
    - task: DotNetCoreCLI@2
      displayName: 'Publication du project $(appname).API'
      inputs:
        command: 'publish'
        publishWebProjects: true
        projects: '**/*$(appname).csproj'
        arguments: '--configuration ${{parameters.buildConfiguration}} --output $(Build.ArtifactStagingDirectory)'
    
    - task: DotNetCoreCLI@2
      displayName: 'Publication du project $(appname).API'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/*$(appname).csproj'
        arguments: '--configuration ${{parameters.buildConfiguration}} --output $(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publication de artifact dans Azure Pipeline'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: ${{parameters.artifactName}}
        publishLocation: 'Container'