parameters:
  - name: buildConfiguration
    type: string
  - name: artifactName
    type: string

jobs:
  - job: 'WebBuild'
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restaurer les packages NuGet'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
    
    - task: DotNetCoreCLI@2
      displayName: 'Génération de la solution'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration ${{parameters.buildConfiguration}}'
    
    - task: DotNetCoreCLI@2
      displayName: 'Execution des tests unitaires'
      inputs:
        command: 'test'
        projects: '**/*UnitTests.csproj'
        arguments: '--configuration ${{parameters.buildConfiguration}}'
    
    - task: DotNetCoreCLI@2
      displayName: 'Publication du project Etudiants.API'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/Etudiants.API.csproj'
        arguments: '--configuration ${{parameters.buildConfiguration}} --output $(Build.ArtifactStagingDirectory)'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publication de artifact dans Azure Pipeline'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: ${{parameters.artifactName}}
        publishLocation: 'Container'