parameters:
  - name: environment
    type: string
  - name: artifactName
    type: string
  - name: serviceConnection
    type: string
  - name: webAppName
    type: string

jobs:
  - deployment: 'WebDeploy'
    pool:
      vmImage: ubuntu-latest
    environment: '${{parameters.environment}}'
    strategy:
     runOnce:
       deploy:
         steps:
         - task: DownloadBuildArtifacts@1
           displayName: 'Télecharger artifact pour le déploiment'
           inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: '${{parameters.artifactName}}'
            downloadPath: '$(System.ArtifactsDirectory)'
            
         - task: AzureWebApp@1
           displayName: 'Déployer dans App Service'
           inputs:
            azureSubscription: '${{parameters.serviceConnection}}'
            appType: 'webApp'
            appName: '${{parameters.webAppName}}'
            package: '$(System.ArtifactsDirectory)/**/*.zip'
