parameters:
  - name: buildConfiguration
    type: string

jobs:
  - job: 'GenerationSolution'
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restaurer les packages NuGet'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
    
    - task: DotNetCoreCLI@2
      displayName: 'Génération de la solution'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration ${{parameters.buildConfiguration}}'
    
    - task: DotNetCoreCLI@2
      displayName: 'Execution des tests unitaires'
      inputs:
        command: 'test'
        projects: '**/*.UnitTests.csproj'
        arguments: '--configuration ${{parameters.buildConfiguration}}'