# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  serviceConnection: 'sc-azure'
  acrServiceConnection: 'sc-container-registry'
  imageRepository: 'emploisapi' 
  tag: '$(Build.BuildId)'

stages:
  - stage: 'Build'
    displayName: 'Génération et push image'
    pool:
      vmImage: ubuntu-latest
    variables:
      dockerfilePath: '**/*Emplois.API/Dockerfile'

    jobs:
      - job: 'Build'
        steps:
        - task: Docker@2
          displayName: 'Génération et push image dans registre de conteneurs'
          inputs:
            containerRegistry: '$(acrServiceConnection)'
            repository: '$(imageRepository)'
            command: 'buildAndPush'
            Dockerfile: '$(dockerfilePath)'
            buildContext: '$(Build.Repository.LocalPath)'

  - stage: 'DeployToDev'
    displayName: 'Déploiment en Dev'
    dependsOn: 'Build'
    pool:
      vmImage: ubuntu-latest
    variables:
      containerRegistry: 'acrmodernrecruit.azurecr.io'
      registryUser: 'acrmodernrecruit'
      registryPwd: 'QzwiOG1rnGtNXXaQntesSuNbHkXpn7GuOkB6qm4PEg+ACRAFX/X4'
      aciName: 'aci-emplois-api'
      env: 'development'

    jobs:
      - deployment: 'DeployToDev'
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps:
              - task: AzureCLI@2
                displayName: 'Déploiment sur Azure Container Instances'
                inputs:
                  azureSubscription: $(serviceConnection)
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: 
                    az container create --resource-group rg-dev-modernrecruit --name $(aciName) --environment-variables ASPNETCORE_ENVIRONMENT=$(env) --image $(containerRegistry)/$(imageRepository):$(tag) --cpu 1 --memory 1 --registry-login-server $(containerRegistry) --registry-username $(registryUser) --registry-password $(registryPwd) --ip-address Public --dns-name-label $(imageRepository) --ports 5555