# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  buildConfiguration: 'Release'
  serviceConnection: 'sc-azure'
  artifactName: 'drop'

stages:
- stage: 'GenerationSolution'
  displayName: 'Generation Solution Modern Recruit'
  jobs:
  - template: templates/generation-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)

- stage: 'DocumentsDeployToDev'
  displayName: 'Documents API Deploy to Dev'
  dependsOn: 'GenerationSolution'
  jobs:
  - job: 'BuildDocuments'
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: 'artifdocuments'
      appname: 'Documents.API'

  - job: 'DeployDocuments'
    dependsOn: 'BuildDocuments'
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: 'artif-documents'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-documents-*'

- stage: 'EmploisDeployToDev'
  displayName: 'Emplois API Deploy to Dev'
  dependsOn: 'GenerationSolution'
  jobs:
  - job: 'BuildEmplois'
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: 'artif-emplois'
      appname: 'Emplois.API'

  - job: 'DeployEmplois'
    dependsOn: 'BuildEmplois'
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: 'artif-emplois'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-emplois-*'

- stage: 'FavorisDeployToDev'
  displayName: 'Favoris API Deploy to Dev'
  dependsOn: 'GenerationSolution'
  jobs:
  - job: 'BuildFavoris'
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: 'artif-favoris'
      appname: 'Favoris.API'

  - job: 'DeployFavoris'
    dependsOn: 'BuildFavoris'
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: 'artif-favoris'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-favoris-*'

- stage: 'PostulationsDeployToDev'
  displayName: 'Postulations API Deploy to Dev'
  dependsOn: 'GenerationSolution'
  jobs:
  - job: 'BuildPostulations'
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: 'artif-postulations'
      appname: 'Postulations.API'

  - job: 'DeployPostulations'
    dependsOn: 'BuildPostulations'
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: 'artif-postulations'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-postulations-*'

- stage: 'MVCDeployToDev'
  displayName: 'MVC API Deploy to Dev'
  dependsOn:
  - 'DocumentsDeployToDev'
  - 'EmploisDeployToDev'
  - 'FavorisDeployToDev'
  - 'PostulationsDeployToDev'
  jobs:
  - job: 'BuildMvc'
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: 'artif-mvc'
      appname: 'MVC'
      publishWebProjects: true

  - job: 'DeployMvc'
    dependsOn: 'BuildMvc'
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: 'artif-mvc'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-mvc-*'