# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  buildConfiguration: 'Release'
  serviceConnection: 'sc-azure'
  artifactName: 'drop'

stages:
- stage: 'GenerationSolution'
  displayName: 'Generation Solution Modern Recruit'
  jobs:
  - template: templates/generation-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)

- stage: 'DocumentsDeployToDev'
  displayName: 'Build et Deploy API Documents to Dev'
  dependsOn: 'GenerationSolution'
  jobs:
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: 'artifdocuments'
      appname: 'Documents.API'

  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: 'artif-documents'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-documents-*'

- stage: 'EmploisDeployToDev'
  displayName: 'Build et Deploy API Emplois to Dev'
  dependsOn: 'GenerationSolution'
  jobs:
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: 'artif-emplois'
      appname: 'Emplois.API'

  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: 'artif-emplois'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-emplois-*'

- stage: 'FavorisDeployToDev'
  displayName: 'Build et Deploy API Favoris to Dev'
  dependsOn: 'GenerationSolution'
  jobs:
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: 'artif-favoris'
      appname: 'Favoris.API'

  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: 'artif-favoris'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-favoris-*'

- stage: 'PostulationsDeployToDev'
  displayName: 'Build et Deploy API Postulations to Dev'
  dependsOn: 'GenerationSolution'
  jobs:
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: 'artif-postulations'
      appname: 'Postulations.API'

  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: 'artif-postulations'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-postulations-*'

- stage: 'MVCDeployToDev'
  displayName: 'Build et Deploy MVC to Dev'
  dependsOn:
  - 'DocumentsDeployToDev'
  - 'EmploisDeployToDev'
  - 'FavorisDeployToDev'
  - 'PostulationsDeployToDev'
  jobs:
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: 'artif-mvc'
      appname: 'MVC'
      publishWebProjects: true

  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: 'artif-mvc'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-mvc-*'