# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  buildConfiguration: 'Release'
  serviceConnection: 'sc-azure'

stages:
- stage: 'Build'
  displayName: 'Generation solution et build projets'
  jobs:

  - job: 'Generation'
  - template: templates/generation-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)

  - job: 'BuildDocuments'
    dependsOn: 'Generation'
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: 'artifdocuments'
      appname: 'Documents.API'

  - job: 'BuildEmplois'
    dependsOn: 'Generation'
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: 'artifemplois'
      appname: 'Emplois.API'

  - job: 'BuildFavoris'
    dependsOn: 'Generation'
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: 'artiffavoris'
      appname: 'Favoris.API'

  - job: 'BuildPostulations'
    dependsOn: 'Generation'
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: 'artifpostulations'
      appname: 'Postulations.API'

  - job: 'BuildMvc'
    dependsOn: 'Generation'
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: 'artifmvc'
      appname: 'MVC'
      publishWebProjects: true

- stage: 'DocumentsDeployToDev'
  displayName: 'Documents API Deploy to Dev'
  dependsOn: 'Build'

  jobs:
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: 'artifdocuments'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-documents-*'

- stage: 'EmploisDeployToDev'
  displayName: 'Emplois API Deploy to Dev'
  dependsOn: 'Build'

  jobs:
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: 'artifemplois'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-emplois-*'

- stage: 'FavorisDeployToDev'
  displayName: 'Favoris API Deploy to Dev'
  dependsOn: 'Build'

  jobs:
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: 'artiffavoris'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-favoris-*'

- stage: 'PostulationsDeployToDev'
  displayName: 'Postulations API Deploy to Dev'
  dependsOn: 'Build'

  jobs:
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: 'artifpostulations'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-postulations-*'

- stage: 'MVCDeployToDev'
  displayName: 'MVC API Deploy to Dev'
  dependsOn:
  - 'DocumentsDeployToDev'
  - 'EmploisDeployToDev'
  - 'FavorisDeployToDev'
  - 'PostulationsDeployToDev'

  jobs:
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: 'artifmvc'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-mvc-*'