# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  buildConfiguration: 'Release'
  serviceConnection: 'sc-azure'
  artifactName: 'drop'

stages:
- stage: 'Build'
  displayName: 'Generation solution Modern Recruit'
  jobs:
  - template: templates/generation-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)

# Documents API build
  - template: templates/build-template.yml
    parameters:
      DependsOn: 'Generation'
      buildConfiguration: $(buildConfiguration)
      artifactName: $(artifactName)
      appname: 'Documents.API'

# Emplois API build
  - template: templates/build-template.yml
    parameters:
      DependsOn: 'Generation'
      buildConfiguration: $(buildConfiguration)
      artifactName: $(artifactName)
      appname: 'Emplois.API'

# Favoris API build
  - template: templates/build-template.yml
    parameters:
      DependsOn: 'Generation'
      buildConfiguration: $(buildConfiguration)
      artifactName: $(artifactName)
      appname: 'Favoris.API'

# Postulations API build
  - template: templates/build-template.yml
    parameters:
      DependsOn: 'Generation'
      buildConfiguration: $(buildConfiguration)
      artifactName: $(artifactName)
      appname: 'Postulations.API'

# MVC build
  - template: templates/build-template.yml
    parameters:
      DependsOn: 'Generation'
      buildConfiguration: $(buildConfiguration)
      artifactName: $(artifactName)
      appname: 'MVC'
      publishWebProjects: true


- stage: 'DocumentsDeployToDev'
  displayName: 'Documents API Deploy to Dev'
  dependsOn: 'Build'

  jobs:
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: 'Documents.API'
      webAppName: 'webapp-documents-35savyvwj5fym'

- stage: 'EmploisDeployToDev'
  displayName: 'Emplois API Deploy to Dev'
  dependsOn: 'Build'

  jobs:
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: 'Emplois.API'
      webAppName: 'webapp-emplois-35savyvwj5fym'

- stage: 'FavorisDeployToDev'
  displayName: 'Favoris API Deploy to Dev'
  dependsOn: 'Build'

  jobs:
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: 'Favoris.API'
      webAppName: 'webapp-favoris-35savyvwj5fym'

- stage: 'PostulationsDeployToDev'
  displayName: 'Postulations API Deploy to Dev'
  dependsOn: 'Build'

  jobs:
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: 'Postulations.API'
      webAppName: 'webapp-postulations-35savyvwj5fym'

- stage: 'MVCDeployToDev'
  displayName: 'MVC API Deploy to Dev'
  dependsOn:
  - 'DocumentsDeployToDev'
  - 'EmploisDeployToDev'
  - 'FavorisDeployToDev'
  - 'PostulationsDeployToDev'

  jobs:
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: 'MVC'
      webAppName: 'webapp-mvc-35savyvwj5fym'

- stage: 'DocumentsDeployToProd'
  displayName: 'Documents API Deploy to Prod'
  dependsOn:
  - 'DocumentsDeployToDev'
  - 'EmploisDeployToDev'
  - 'FavorisDeployToDev'
  - 'PostulationsDeployToDev'
  - 'MVCDeployToDev'

  jobs:
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Prod'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: 'Documents.API'
      webAppName: 'webapp-documents-tcalemx7mxa56'

- stage: 'EmploisDeployToProd'
  displayName: 'Emplois API Deploy to Prod'
  dependsOn:
  - 'DocumentsDeployToDev'
  - 'EmploisDeployToDev'
  - 'FavorisDeployToDev'
  - 'PostulationsDeployToDev'
  - 'MVCDeployToDev'

  jobs:
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Prod'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: 'Emplois.API'
      webAppName: 'webapp-emplois-tcalemx7mxa56'

- stage: 'FavorisDeployToProd'
  displayName: 'Favoris API Deploy to Prod'
  dependsOn:
  - 'DocumentsDeployToDev'
  - 'EmploisDeployToDev'
  - 'FavorisDeployToDev'
  - 'PostulationsDeployToDev'
  - 'MVCDeployToDev'

  jobs:
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Prod'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: 'Favoris.API'
      webAppName: 'webapp-favoris-tcalemx7mxa56'

- stage: 'PostulationsDeployToProd'
  displayName: 'Postulations API Deploy to Prod'
  dependsOn:
  - 'DocumentsDeployToDev'
  - 'EmploisDeployToDev'
  - 'FavorisDeployToDev'
  - 'PostulationsDeployToDev'
  - 'MVCDeployToDev'

  jobs:
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Prod'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: 'Postulations.API'
      webAppName: 'webapp-postulations-tcalemx7mxa56'

- stage: 'MVCDeployToProd'
  displayName: 'MVC Deploy to Prod'
  dependsOn:
  - 'DocumentsDeployToProd'
  - 'EmploisDeployToProd'
  - 'FavorisDeployToProd'
  - 'PostulationsDeployToProd'

  jobs:
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Prod'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: 'MVC'
      webAppName: 'webapp-mvc-tcalemx7mxa56'