# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  buildConfiguration: 'Release'
  serviceConnection: 'sc-azure'
  artifactName: 'drop'

stages:
- stage: 'Generation'
  displayName: 'Generation solution Modern Recruit'
  jobs:
  - template: templates/generation-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)

- stage: 'DocumentsDeployToDev'
  displayName: 'Documents API Deploy to Dev'
  dependsOn: 'Generation'
  variables:
    appname: 'Documents.API'

  jobs:
  - job: 'BuildDocuments'
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: $(artifactName)
      appname: $(appname)

  - job: 'DeployDocuments'
    dependsOn: 'BuildDocuments'
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: $(appname)
      webAppName: 'webapp-documents-35savyvwj5fym'

- stage: 'EmploisDeployToDev'
  displayName: 'Emplois API Deploy to Dev'
  dependsOn: 'Generation'
  variables:
    appname: 'Emplois.API'

  jobs:
  - job: 'BuildEmplois'
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: $(artifactName)
      appname: $(appname)

  - job: 'DeployEmplois'
    dependsOn: 'BuildEmplois'
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: $(appname)
      webAppName: 'webapp-emplois-35savyvwj5fym'

- stage: 'FavorisDeployToDev'
  displayName: 'Favoris API Deploy to Dev'
  dependsOn: 'Generation'
  variables:
    appname: 'Favoris.API'

  jobs:
  - job: 'BuildFavoris'
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: $(artifactName)
      appname: $(appname)

  - job: 'DeployFavoris'
    dependsOn: 'BuildFavoris'
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: $(appname)
      webAppName: 'webapp-favoris-35savyvwj5fym'

- stage: 'PostulationsDeployToDev'
  displayName: 'Postulations API Deploy to Dev'
  dependsOn: 'Generation'
  variables:
    appname: 'Postulations.API'

  jobs:
  - job: 'BuildPostulations'
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: $(artifactName)
      appname: $(appname)

  - job: 'DeployPostulations'
    dependsOn: 'BuildPostulations'
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: $(appname)
      webAppName: 'webapp-postulations-35savyvwj5fym'

- stage: 'MVCDeployToDev'
  displayName: 'MVC API Deploy to Dev'
  dependsOn:
  - 'DocumentsDeployToDev'
  - 'EmploisDeployToDev'
  - 'FavorisDeployToDev'
  - 'PostulationsDeployToDev'
  variables:
    appname: 'MVC'

  jobs:
  - job: 'BuildMvc'
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: $(artifactName)
      appname: $(appname)
      publishWebProjects: true

  - job: 'DeployMvc'
    dependsOn: 'BuildMvc'
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: $(appname)
      webAppName: 'webapp-mvc-35savyvwj5fym'

- stage: 'DocumentsDeployToProd'
  displayName: 'Documents API Deploy to Prod'
  dependsOn:
  - 'DocumentsDeployToDev'
  - 'EmploisDeployToDev'
  - 'FavorisDeployToDev'
  - 'PostulationsDeployToDev'
  - 'MVCDeployToDev'

  variables:
    appname: 'Documents.API'

  jobs:
  - job: 'DeployDocuments'
    dependsOn: 'BuildDocuments'
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Prod'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: $(appname)
      webAppName: 'webapp-documents-35savyvwj5fym'

- stage: 'EmploisDeployToProd'
  displayName: 'Emplois API Deploy to Prod'
  dependsOn:
  - 'DocumentsDeployToDev'
  - 'EmploisDeployToDev'
  - 'FavorisDeployToDev'
  - 'PostulationsDeployToDev'
  - 'MVCDeployToDev'

  variables:
    appname: 'Emplois.API'

  jobs:
  - job: 'DeployEmplois'
    dependsOn: 'BuildEmplois'
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Prod'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: $(appname)
      webAppName: 'webapp-emplois-35savyvwj5fym'

- stage: 'FavorisDeployToProd'
  displayName: 'Favoris API Deploy to Prod'
  dependsOn:
  - 'DocumentsDeployToDev'
  - 'EmploisDeployToDev'
  - 'FavorisDeployToDev'
  - 'PostulationsDeployToDev'
  - 'MVCDeployToDev'

  variables:
    appname: 'Favoris.API'

  jobs:
  - job: 'DeployFavoris'
    dependsOn: 'BuildFavoris'
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Prod'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: $(appname)
      webAppName: 'webapp-favoris-35savyvwj5fym'

- stage: 'PostulationsDeployToProd'
  displayName: 'Postulations API Deploy to Prod'
  dependsOn:
  - 'DocumentsDeployToDev'
  - 'EmploisDeployToDev'
  - 'FavorisDeployToDev'
  - 'PostulationsDeployToDev'
  - 'MVCDeployToDev'

  variables:
    appname: 'Postulations.API'

  jobs:
  - job: 'DeployPostulations'
    dependsOn: 'BuildPostulations'
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Prod'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: $(appname)
      webAppName: 'webapp-postulations-35savyvwj5fym'

- stage: 'MVCDeployToProd'
  displayName: 'MVC Deploy to Prod'
  dependsOn:
  - 'DocumentsDeployToProd'
  - 'EmploisDeployToProd'
  - 'FavorisDeployToProd'
  - 'PostulationsDeployToProd'

  variables:
    appname: 'MVC'

  jobs:
  - job: 'DeployMvc'
    dependsOn: 'BuildMvc'
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Prod'
      artifactName: $(artifactName)
      serviceConnection: $(serviceConnection)
      appName: $(appname)
      webAppName: 'webapp-mvc-35savyvwj5fym'